import tkinter
from CTkTrimSlider.custom_rendering import CustomDrawEngine as CustomDrawEngine
from collections.abc import Callable as Callable
from customtkinter.windows.widgets.core_widget_classes import CTkBaseClass
from typing import Any

class CTkTrimSlider(CTkBaseClass):
    def __init__(self, master: object, width: int | None = None, height: int | None = None, corner_radius: int | None = None, border_width: int | None = None, outer_button_length: int | None = None, outer_button_corner_radius: int | None = None, center_button_corner_radius: int | None = None, bg_color: str | tuple[str] = 'transparent', fg_color: str | tuple[str] | None = None, border_color: str | tuple[str] = 'transparent', progress_color: str | tuple[str] | None = None, button_color: str | tuple[str] | None = None, button_hover_color: str | tuple[str] | None = None, from_: int = 0, to: int = 1, number_of_steps: int = 1000, state: str = 'normal', hover: bool = True, orientation: str = 'horizontal', left_button_command: Callable[[float], None] | None = None, right_button_command: Callable[[float], None] | None = None, center_button_command: Callable[[float], None] | None = None, left_button_var: tkinter.Variable | None = None, right_button_var: tkinter.Variable | None = None, center_button_var: tkinter.Variable | None = None, button_blocking: bool = False, **kwargs) -> None: ...
    def bind(self, sequence: str | None = None, command: Callable[[Any], int | float] | None = None, add: str | bool = True) -> None: ...
    def unbind(self, sequence: str | None = None, funcid: str | None = None) -> None: ...
    def configure(self, require_redraw: bool = False, **kwargs) -> None: ...
    def cget(self, attribute_name: str) -> Any: ...
    def get(self, attribute_name: str) -> float: ...
    def set(self, attribute_name, input_value, from_variable_callback: bool = False) -> None: ...
    def focus(self) -> Any: ...
    def focus_set(self) -> Any: ...
    def focus_force(self) -> Any: ...
