from customtkinter.windows.widgets.core_rendering import CTkCanvas as CTkCanvas, DrawEngine

class CustomDrawEngine(DrawEngine):
    def __init__(self, canvas: CTkCanvas) -> None: ...
    def draw_rounded_slider_with_border_and_3_buttons(self, width: int | float, height: int | float, corner_radius: int | float, border_width: int | float, outer_button_length: int | float, outer_button_corner_radius: int | float, center_button_corner_radius: int | float, lbutton_value: int | float, rbutton_value: int | float, cbutton_value: int | float, orientation: str) -> bool: ...
